version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: task_manager_api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: taskuser
      DB_PASSWORD: taskpass
      DB_NAME: task_manager
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data: